[package]
name = "md5lib"
version = "0.1.0"
authors = ["Scott McCarthy <smccarthy@shelltechworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"